steps:
  # 1. Build image
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "--no-cache",
        "-t",
        "asia-south1-docker.pkg.dev/ai-project-488008/cloud-run-source-deploy/eleven-backend:$COMMIT_SHA",
        "."
      ]
  # 2. Push image
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "asia-south1-docker.pkg.dev/ai-project-488008/cloud-run-source-deploy/eleven-backend:$COMMIT_SHA"
      ]
  # 3. Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "eleven-backend",
        "--image",
        "asia-south1-docker.pkg.dev/ai-project-488008/cloud-run-source-deploy/eleven-backend:$COMMIT_SHA",
        "--region",
        "asia-south1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--service-account",
        "712008615735-compute@developer.gserviceaccount.com",
        "--project",
        "ai-project-488008",
        "--timeout",
        "300s",
        "--quiet"
      ]
images:
  - asia-south1-docker.pkg.dev/ai-project-488008/cloud-run-source-deploy/eleven-backend:$COMMIT_SHA
options:
  logging: CLOUD_LOGGING_ONLY
